export const COPY = {
  it: {
    login: 'Accedi',
    ctaNav: 'Richiedi accesso',
    nav: [
      { id: 'home', label: 'Home' },
      { id: 'product', label: 'Prodotto' },
      { id: 'features', label: 'Funzionalità' },
      { id: 'pricing', label: 'Prezzi' },
      { id: 'support', label: 'Supporto' },
      { id: 'contact', label: 'Contatti' },
    ],
    hero: {
      eyebrow: 'Piattaforma di recupero crediti',
      pre: 'Meno rischio,',
      mid1: 'più incassi.',
      mid2: '',
      end: 'Con ryzk.io.',
      sub: 'Automazioni intelligenti, scoring predittivo e workflow modulari. Pensati per ogni azienda che vuole incassare di più, rischiare di meno.',
      cta: 'Richiedi accesso',
      secondary: 'Guarda la demo',
      trust: 'Scelto da team finance, legal e operations in tutta Italia.',
      card1: 'Automazione attiva',
      card1Sub: '142 pratiche in lavorazione',
      stat1: 'tasso di recupero',
      stat2: 'tempo medio incasso',
      stat3: 'go-live medio',
    },
    how: {
      eyebrow: 'Come funziona',
      title: 'Da prima solicitazione a incasso, senza attriti.',
      sub: 'Quattro fasi orchestrate da ryzk.io — dalla ricezione delle posizioni fino al saldo, con ogni contatto tracciato.',
      steps: [
        { title: 'Importa', desc: 'Collega CRM, ERP o fogli Excel. ryzk.io normalizza anagrafiche e scadenzari in minuti.' },
        { title: 'Segmenta', desc: 'Il motore di scoring classifica ogni posizione per probabilità di recupero e tono più efficace.' },
        { title: 'Automatizza', desc: 'Email, SMS, chiamate e lettere certificate partono in sequenza, sulla base di risposte e pagamenti.' },
        { title: 'Incassa', desc: 'Riconciliazione automatica, reportistica live e payout diretti al tuo conto.' },
      ],
    },
    product: {
      eyebrow: 'Prodotto',
      title: 'Una dashboard che fa il lavoro pesante.',
      sub: 'Tutto quello che serve al tuo team credit — KPI live, coda lavorazioni e automazioni componibili — in un\'unica interfaccia.',
      nav: ['Panoramica', 'Portafoglio', 'Automazioni', 'Anagrafiche', 'Pagamenti', 'Report'],
      live: 'LIVE · aggiornato ora',
      portfolio: 'Portafoglio crediti',
      kpis: [
        { label: 'Esposto totale', value: '€ 4.28M', delta: '+2.1%', up: true },
        { label: 'Recuperato 30g', value: '€ 1.12M', delta: '+38%', up: true },
        { label: 'DSO medio', value: '47 gg', delta: '-12 gg', up: true },
        { label: 'Tasso risposta', value: '62%', delta: '+9%', up: true },
      ],
      chartTitle: 'Recupero cumulato · ultimi 90 giorni',
      legend1: 'Previsto',
      legend2: 'Effettivo',
      queueTitle: 'Coda di lavorazione',
      queue: [
        { initials: 'MC', name: 'Marchetti & Co. Srl', meta: 'Sollecito 2 · scaduto 14gg', amount: '€ 12.480' },
        { initials: 'PL', name: 'Panella Logistica', meta: 'Promessa pagamento · oggi', amount: '€ 3.220' },
        { initials: 'NV', name: 'Nuvola Veneta SpA', meta: 'Piano rate attivo', amount: '€ 28.900' },
        { initials: 'DG', name: 'De Giorgi Automotive', meta: 'In negoziazione', amount: '€ 7.650' },
      ],
      automationTitle: 'Automazioni attive',
      automations: [
        { title: 'Sollecito soft', sub: 'T+3 giorni dalla scadenza' },
        { title: 'Telefonata AI', sub: 'T+10 · script dinamico' },
        { title: 'Diffida PEC', sub: 'T+30 · con allegati' },
        { title: 'Piano rate', sub: 'Proposto se importo > €5k' },
      ],
    },
    metrics: {
      eyebrow: 'Risultati',
      title: 'Numeri veri, da clienti veri.',
      sub: 'Media rilevata sui primi 90 giorni di utilizzo. Ogni dato è misurato dentro la piattaforma.',
      items: [
        { value: '+38%', label: 'Tasso di recupero', desc: 'Sulle posizioni scadute oltre 30 giorni.' },
        { value: '-52%', label: 'Tempo di incasso', desc: 'Riduzione media del DSO nei primi 6 mesi.' },
        { value: '14 giorni', label: 'Go-live', desc: 'Dall\'onboarding alla prima campagna attiva.' },
        { value: '98.2%', label: 'Uptime', desc: 'SLA garantito su infrastruttura europea.' },
      ],
    },
    testimonials: {
      eyebrow: 'Dicono di noi',
      title: 'Team finance che hanno smesso di rincorrere pagamenti.',
      items: [
        { quote: 'Abbiamo dimezzato il DSO in quattro mesi. Il team credit ora chiude più pratiche, non più email.', name: 'Giulia Ferrara', role: 'CFO, Nuvola Veneta SpA', initials: 'GF' },
        { quote: 'Le automazioni PEC e il piano rate proposto in automatico sono stati un cambio di passo netto.', name: 'Andrea Conti', role: 'Credit Manager, Panella Group', initials: 'AC' },
        { quote: 'L\'integrazione con SAP è stata viva in 9 giorni. Non avevo mai visto un onboarding così.', name: 'Sara Bellini', role: 'Head of Operations, Marchetti & Co.', initials: 'SB' },
      ],
    },
    integrations: {
      eyebrow: 'Integrazioni',
      title: 'Si collega a tutto quello che già usi.',
      sub: 'CRM, ERP, gateway di pagamento, email provider. REST API e webhook firmati per il resto.',
      foot: 'Vedi tutte le integrazioni',
    },
    pricing: {
      eyebrow: 'Piani',
      title: 'Prezzi che crescono con te.',
      sub: 'Paghi solo sul recuperato. Nessun costo nascosto, nessun canone di setup.',
      popular: 'Più scelto',
      plans: [
        {
          name: 'Starter',
          price: '€ 390',
          unit: '/mese',
          desc: 'Per team credit fino a 3 persone. Automazioni di base e reportistica.',
          cta: 'Inizia',
          features: ['Fino a 500 pratiche/mese', 'Automazioni email & SMS', 'Dashboard live', 'Supporto via chat'],
        },
        {
          name: 'Scale',
          price: '€ 1.290',
          unit: '/mese',
          desc: 'Per chi gestisce portafogli strutturati e vuole più leve di automazione.',
          cta: 'Richiedi accesso',
          featured: true,
          features: ['Fino a 5.000 pratiche/mese', 'PEC, telefonate AI, piani rate', 'Scoring predittivo', 'Integrazioni SAP/Oracle', 'Success manager dedicato'],
        },
        {
          name: 'Enterprise',
          price: 'Su misura',
          unit: '',
          desc: 'Per banche, utility, gruppi industriali con volumi elevati.',
          cta: 'Parla con noi',
          features: ['Volume illimitato', 'SLA 99.9% + ambiente dedicato', 'Data residency UE', 'SSO + audit log avanzato', 'Onboarding con team senior'],
        },
      ],
    },
    cta: {
      title: 'Pronto a incassare prima?',
      sub: 'Ti mostriamo ryzk.io sui tuoi numeri in una demo di 30 minuti.',
      primary: 'Richiedi accesso',
      secondary: 'Scrivici',
    },
    footer: {
      tag: 'La piattaforma di recupero crediti per ogni azienda. Costruita in Italia, pensata per l\'Europa.',
      rights: 'Tutti i diritti riservati.',
      cols: [
        { title: 'Prodotto', items: ['Panoramica', 'Automazioni', 'Scoring', 'API', 'Changelog'] },
        { title: 'Azienda', items: ['Chi siamo', 'Clienti', 'Partner', 'Carriere', 'Contatti'] },
        { title: 'Risorse', items: ['Guide', 'Blog', 'Webinar', 'Stato servizio', 'Sicurezza'] },
        { title: 'Legale', items: ['Privacy', 'Termini', 'Cookie', 'DPA', 'GDPR'] },
      ],
    },
  },
  en: {
    login: 'Login',
    ctaNav: 'Request access',
    nav: [
      { id: 'home', label: 'Home' },
      { id: 'product', label: 'Product' },
      { id: 'features', label: 'Features' },
      { id: 'pricing', label: 'Pricing' },
      { id: 'support', label: 'Support' },
      { id: 'contact', label: 'Contact' },
    ],
    hero: {
      eyebrow: 'Credit recovery platform',
      pre: 'Less risk,',
      mid1: 'more cash.',
      mid2: '',
      end: 'With ryzk.io.',
      sub: 'Smart automations, predictive scoring and modular workflows. Built for any company that wants to collect more — and risk less.',
      cta: 'Request access',
      secondary: 'Watch the demo',
      trust: 'Trusted by finance, legal and operations teams across Europe.',
      card1: 'Automation live',
      card1Sub: '142 cases in progress',
      stat1: 'recovery rate',
      stat2: 'avg. time to cash',
      stat3: 'median go-live',
    },
    how: {
      eyebrow: 'How it works',
      title: 'From first reminder to payment, without the friction.',
      sub: 'Four stages orchestrated by ryzk.io — from intake all the way to settlement, with every touchpoint tracked.',
      steps: [
        { title: 'Import', desc: 'Plug in your CRM, ERP or spreadsheets. ryzk.io normalizes accounts and due dates in minutes.' },
        { title: 'Segment', desc: 'Predictive scoring ranks every case by likelihood to recover and most effective tone.' },
        { title: 'Automate', desc: 'Emails, SMS, AI calls and certified letters fire in sequence — reacting to replies and payments.' },
        { title: 'Get paid', desc: 'Automatic reconciliation, live reporting and direct payouts to your account.' },
      ],
    },
    product: {
      eyebrow: 'Product',
      title: 'A dashboard that does the heavy lifting.',
      sub: 'Everything your credit team needs — live KPIs, work queue and composable automations — in one interface.',
      nav: ['Overview', 'Portfolio', 'Automations', 'Accounts', 'Payments', 'Reports'],
      live: 'LIVE · updated now',
      portfolio: 'Receivables portfolio',
      kpis: [
        { label: 'Total exposure', value: '€ 4.28M', delta: '+2.1%', up: true },
        { label: 'Recovered 30d', value: '€ 1.12M', delta: '+38%', up: true },
        { label: 'Avg. DSO', value: '47 d', delta: '-12 d', up: true },
        { label: 'Response rate', value: '62%', delta: '+9%', up: true },
      ],
      chartTitle: 'Cumulative recovery · last 90 days',
      legend1: 'Forecast',
      legend2: 'Actual',
      queueTitle: 'Work queue',
      queue: [
        { initials: 'MC', name: 'Marchetti & Co. Srl', meta: 'Reminder 2 · 14d overdue', amount: '€ 12,480' },
        { initials: 'PL', name: 'Panella Logistics', meta: 'Promise to pay · today', amount: '€ 3,220' },
        { initials: 'NV', name: 'Nuvola Veneta SpA', meta: 'Payment plan active', amount: '€ 28,900' },
        { initials: 'DG', name: 'De Giorgi Automotive', meta: 'Negotiating', amount: '€ 7,650' },
      ],
      automationTitle: 'Active automations',
      automations: [
        { title: 'Soft reminder', sub: 'T+3 days past due' },
        { title: 'AI phone call', sub: 'T+10 · dynamic script' },
        { title: 'Legal PEC', sub: 'T+30 · with attachments' },
        { title: 'Payment plan', sub: 'Proposed if amount > €5k' },
      ],
    },
    metrics: {
      eyebrow: 'Results',
      title: 'Real numbers, from real customers.',
      sub: 'Averages measured in the first 90 days of use. Every number is tracked inside the platform.',
      items: [
        { value: '+38%', label: 'Recovery rate', desc: 'On accounts overdue more than 30 days.' },
        { value: '-52%', label: 'Time to cash', desc: 'Average DSO reduction over the first 6 months.' },
        { value: '14 days', label: 'Go-live', desc: 'From onboarding to first live campaign.' },
        { value: '98.2%', label: 'Uptime', desc: 'SLA guaranteed on European infrastructure.' },
      ],
    },
    testimonials: {
      eyebrow: 'Testimonials',
      title: 'Finance teams that stopped chasing payments.',
      items: [
        { quote: 'We halved DSO in four months. The credit team now closes more cases, not more emails.', name: 'Giulia Ferrara', role: 'CFO, Nuvola Veneta SpA', initials: 'GF' },
        { quote: 'PEC automation and auto-proposed payment plans were a clear step change for us.', name: 'Andrea Conti', role: 'Credit Manager, Panella Group', initials: 'AC' },
        { quote: 'The SAP integration went live in 9 days. I had never seen an onboarding that fast.', name: 'Sara Bellini', role: 'Head of Operations, Marchetti & Co.', initials: 'SB' },
      ],
    },
    integrations: {
      eyebrow: 'Integrations',
      title: 'Connects to everything you already use.',
      sub: 'CRM, ERP, payment gateways, email providers. REST API and signed webhooks for the rest.',
      foot: 'See all integrations',
    },
    pricing: {
      eyebrow: 'Plans',
      title: 'Pricing that scales with you.',
      sub: 'Pay only on what you recover. No hidden costs, no setup fees.',
      popular: 'Most chosen',
      plans: [
        {
          name: 'Starter',
          price: '€ 390',
          unit: '/month',
          desc: 'For credit teams up to 3 people. Core automations and reporting.',
          cta: 'Start',
          features: ['Up to 500 cases/month', 'Email & SMS automations', 'Live dashboard', 'Chat support'],
        },
        {
          name: 'Scale',
          price: '€ 1,290',
          unit: '/month',
          desc: 'For structured portfolios that need more automation levers.',
          cta: 'Request access',
          featured: true,
          features: ['Up to 5,000 cases/month', 'PEC, AI calls, payment plans', 'Predictive scoring', 'SAP/Oracle integrations', 'Dedicated success manager'],
        },
        {
          name: 'Enterprise',
          price: 'Custom',
          unit: '',
          desc: 'For banks, utilities, industrial groups with high volumes.',
          cta: 'Talk to us',
          features: ['Unlimited volume', 'SLA 99.9% + dedicated env.', 'EU data residency', 'SSO + advanced audit log', 'Senior onboarding team'],
        },
      ],
    },
    cta: {
      title: 'Ready to get paid faster?',
      sub: 'We\'ll show ryzk.io on your own numbers in a 30-minute demo.',
      primary: 'Request access',
      secondary: 'Write us',
    },
    footer: {
      tag: 'The credit recovery platform for every company. Built in Italy, designed for Europe.',
      rights: 'All rights reserved.',
      cols: [
        { title: 'Product', items: ['Overview', 'Automations', 'Scoring', 'API', 'Changelog'] },
        { title: 'Company', items: ['About', 'Customers', 'Partners', 'Careers', 'Contact'] },
        { title: 'Resources', items: ['Guides', 'Blog', 'Webinars', 'Status', 'Security'] },
        { title: 'Legal', items: ['Privacy', 'Terms', 'Cookies', 'DPA', 'GDPR'] },
      ],
    },
  },
};
